name: widgetbook_workspace
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  widgetarium:
    path: ../

  widgetbook: ^3.19.0
  widgetbook_annotation: ^3.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  widgetbook_generator: ^3.19.0
  build_runner: ^2.10.1

flutter:
  uses-material-design: true
